# https://medium.com/@RupaniChirag/auto-publish-react-angular-front-end-app-to-github-pages-3ca1641bfdf6

variables:
  SSH_PUBLISH_PASS: $(PUBLISHKEY)
  SSH_PUBLIC_KEY: $(PUBLICKEY)
  SSH_SECURE_FILE: $(SECUREFILE)
  SSH_USER_EMAIL: $(USER_EMAIL)
  SSH_USER_NAME: $(USER_NAME)

trigger:
  - deploy

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - task: DownloadSecureFile@1
    name: mySecureFile
    inputs:
      secureFile: "$(SSH_SECURE_FILE)"
      retryCount: "2"

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: ""
      sshPublicKey: "$(SSH_PUBLIC_KEY)"
      sshPassphrase: "$(SSH_PUBLISH_PASS)"
      sshKeySecureFile: "$(SSH_SECURE_FILE)"

  - script: |
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git config --local user.email "$(USER_EMAIL)"
      git config --local user.name "$(USER_NAME)"
      npm install --no-audit --progress=false
      npm run deploy
    displayName: "npm install and deploy"