export const ALERT_SEVERITY_ERROR = "ALERT_SEVERITY_ERROR";
export const ALERT_SEVERITY_WARNING = "ALERT_SEVERITY_WARNING";
export const ALERT_SEVERITY_INFO = "ALERT_SEVERITY_INFO";
export const ALERT_SEVERITY_SUCCESS = "ALERT_SEVERITY_SUCCESS";

export type AlertSeverityTypes = typeof ALERT_SEVERITY_ERROR | typeof ALERT_SEVERITY_WARNING | typeof ALERT_SEVERITY_INFO | typeof ALERT_SEVERITY_SUCCESS;